FROM node:18.0.0-alpine
WORKDIR /app
RUN cd /app
COPY . .
# pri kazde zmene zdrojaku se pri docker buildu instaluji znovu knihovny (nefunguje docker layer cache)
COPY package*.json ./
RUN npm install
ENTRYPOINT ["npm", "run", "build"]

FROM nginx:1.21.6-alpine
RUN rm /usr/share/nginx/html/index.html
COPY --from=0 ./build /usr/share/nginx/html/.