FROM node:18.0.0-alpine
WORKDIR /app
RUN cd /app
COPY . .
# pri kazde zmene zdrojaku se pri docker buildu instaluji znovu knihovny (nefunguje docker layer cache)
COPY package*.json ./
RUN npm install
ENTRYPOINT ["npm", "run", "start"]

